language: ruby
sudo: false
rvm:
  - 2.3.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script: bundle exec jekyll build

script: travis_retry bundle exec htmlproofer --url-ignore "/www.tomesh.net/,/tomesh.net/" ./_site

notifications:
  email: false