# Permalinks
permalink: pretty

# Asset compiling
sass:
  style: :compressed

# Site settings
title: Toronto Mesh
email: hi@tomesh.net
description: We are building a mesh network in Toronto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomesh.net" # the base hostname & protocol for your site
github_username: tomeshnet

# Build settings
markdown: kramdown

# Excluded folders
exclude: [scripts]